#!/bin/bash

# Copyright (C) 2020 Grzegorz Kociołek (Dark565)
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.


function help() {
echo "\
 Usage: $(basename $0) [option]... mount
 -h,--help			Show this help;
 -p,--pid-only			List only pids without a list of open files;
 -nc,--nocolors			Don't print colors;

 -k,--kill SIGNAL		Send a SIGNAL to each detected process.
				Signal is presented by appropiate number or name (eg. SIGTERM or 15)
				List of available signals can be displayed with 'kill -l' command;

 -c,--command COMMAND		Execute a COMMAND with the process pid as the argument."
}

function kill_num() {
	/bin/kill -n "$1" "$2"
}

function kill_name() {
	/bin/kill -s "$1" "$2"
}

function cmd() {
	${SHELL} -c "$1" -a "$2" &
}

function fs_mount_from_path() {
	df --output=target "$1" 2>/dev/null | tail -n 1 &

	# Go around a bug with a few block devices.
	# When df tries to read file system from them, kernel sleeps it for the eternity
	T_PID=$(jobs -p)
	if grep 'sleeping' /proc/${T_PID}/status >/dev/null 2>&1
	then
		kill $T_PID
		return 1
	fi
		
}

function resolve_fd_flags() {
	local info_array flags
	readarray -n2 info_array <"$1"
	printf -v flags ${info_array[1]#*:}
	case $((${flags} & 0x3)) in
		2 ) RESOLVED_FLAGS="r+w";;
		1 ) RESOLVED_FLAGS="w  ";;
		0 ) RESOLVED_FLAGS="r  ";;
	esac
}

function print_pid_info() {
	[[ -z ${FOUND} ]] || return 1
	FOUND=1

	local USERID="$(stat -c %u "/proc/${PID}")"
	local USERNAME="$(id -un "${USERID}")"

	printf "\n---  ${GREEN}${USERNAME} [${USERID}]${NOCOLOR}  ---\n"
	printf "${GREEN}${PID}${NOCOLOR} ( $(readlink "/proc/${PID}/exe") )\n"

	if [[ $KILL == 1 ]]; then
		${KILL_FUNC} "${ARG_CMD}" "${PID}"

	elif [[ $CMD == 1 ]]; then
		cmd "${ARG_CMD}" "${PID}"
	fi


}

# Try to read link with builtin functions.
# If they will fail, try to call an external program.
read_link() {
	local link=$1
	if cd -P "${link}" 2>/dev/null; then
		READ_LINK="${PWD}"
		cd - >/dev/null
	elif ! READ_LINK=$(readlink -f "${link}"); then
		return 1
	fi
}

check_fs() {
	local directory=$1
	local check_for=$2

	[[ $(fs_mount_from_path "${directory}") == ${check_for} ]]
}

check_fs_from_link() {
	local link=$1
	local check_for=$2

	read_link "${link}"
	check_fs "${READ_LINK}" "${check_for}"
}

# Check arguments
case $1 in
	"-h" | "--help" )
		help 1
		exit 0
		;;
	"-k" | "--kill" )
		KILL=1
		ARG_CMD=$2

		if [[ $2 =~ ^[0-9]+$ ]]
		then
			KILL_FUNC=kill_num
		else
			KILL_FUNC=kill_name
		fi

		shift 2

		;;
	"-c" | "--command" )
		CMD=1
		ARG_CMD=$2

		shift 2
		;;
esac

START_FS=${1} #FS argument
# Get file system's mount point from the argument
FS_PATH="$(fs_mount_from_path "${START_FS}")"
if [[ ! $? -eq 0 ]]
then
	echo "$(basename $0): Error with reading file system from file" 1>&2
	exit 1
fi

GREEN="\e[1;32m"
RED="\e[1;31m"
ORANGE="\e[1;33m"
NOCOLOR="\e[0m"

printf "${GREEN}These programs use this file system:${NOCOLOR}\n"

# Get all processes using the file system and iterate through them
for PID in $(fuser -m "${FS_PATH}" 2>/dev/null)
do
	cd "/proc/${PID}" 2>/dev/null || continue

	if check_fs_from_link cwd "${FS_PATH}" 2>/dev/null; then
		print_pid_info
		printf "${RED}->    	[pwd] ${NOCOLOR}${READ_LINK}\n"
	fi

	cd fd 2>/dev/null || continue
	ls | while read -r LINK
	do
		if check_fs_from_link ${LINK} "${FS_PATH}" 2>/dev/null; then
			print_pid_info
			resolve_fd_flags "../fdinfo/${LINK}"
			printf "${RED}-> ${ORANGE}${RESOLVED_FLAGS}${RED}	[${LINK}] ${NOCOLOR}${READ_LINK}\n"
		fi
	done

	unset FOUND
done
